services:
  db:
    image: postgres:latest
    networks:
      - backend
    ports:
      - 5432:5432

    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db

    # volumes:
    #   - ./database:/docker-entrypoint-initdb.d/

    
  adminer:
    image: adminer:latest
    networks:
      - backend
    ports:
      - 8081:8080

    restart: always

    depends_on:
      - db

networks:
  backend:
    driver: bridge
